= Frequently Asked Questions

== How do I build DDF?
See the https://github.com/codice/ddf/blob/master/README.md#building[build instructions] on Github.

=== How do I run it?
Simply unzip the distribution that was generated by the build. Run the executable at `bin/ddf.bat` or `bin/ddf`.

== Where do I find additional information or documentation?
The xref:introduction/introduction.adoc[Documentation] page has complete documentation for DDF.

=== How do I contribute to DDF?
Please see http://www.codice.org/contributing[contributor guidelines] for information on becoming a contributor.

=== What is the copyright/license of the DDF software?
This is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. A copy of the GNU Lesser General Public License is distributed along with this program and can be found at http://www.gnu.org/licenses/lgpl.html.
